modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/noobanidus/darktribute/issues"
license="https://github.com/noobanidus/darktribute/blob/master/LICENSE"
[[mods]]
modId="darktribute"
version="${file.jarVersion}"
displayName="Dark Tribute"
displayURL="https://minecraft.curseforge.com/projects/dark-tribute"
logoFile="logo.png"
authors="Noobanidus"
description='''
Rewards you for making a darker kind of tribute.
'''
[[dependencies.DarkTribute]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.DarkTribute]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
